name: Push Release to HomeBrew repository

on:
  workflow_dispatch:

jobs:
  push-release-homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.13
        shell: bash

      - name: Push Release to HomeBrew repository
        run: ./scripts/publish-to-homebrew-repo.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }} # PAT with permissions to push to run-llama/homebrew-liteparse
